pur_beurre_lm/healthier_food/urls.py
#! /usr/bin/env python3
# coding: utf-8

from django.urls import path

from . import views

urlpatterns = [
    path('search', views.search, name='search'),
    path('substitute/<int:unhealthy_product_code>', views.substitute, name='substitute'),
    path('details/<int:product_code>', views.details, name='details'),
    path('new_account', views.new_account, name='new_account'),
    path('account_creation', views.account_creation, name='account_creation'),
    path('login', views.login_user, name='login'),
    path('my_account', views.my_account, name='my_account'),
    path('favorites', views.favorites, name='favorites'),
    path('add_favorite/<int:favorite_code>', views.add_favorite, name='add_favorite'),
    path('logout', views.logout_user, name='logout'),
]

pur_beurre_lm/pur_beurre_lm/urls.py
#! /usr/bin/env python3
# coding: utf-8

"""pur_beurre_lm URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from healthier_food import views

urlpatterns = [
    path('home/', views.home),
    path('healthier_food/', include(('healthier_food.urls', 'healthier_food'), namespace='healthier_food')),
    # path('admin/', admin.site.urls), on change le nom de la route 'admin' par défaut pour un minimum de sécurité
    path('admin_purbeurre/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

pur_beurre_lm/healthier_food/models.py
#! /usr/bin/env python3
# coding: utf-8

from django.db import models
# from django.contrib.auth.models import AbstractUser


# class TimestampedModel(models.Model):
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     class Meta:
#         abstract = True  # Une classe abstraite ne peut pas être instanciée. Django ne la considère donc pas comme un modèle à part entière, il ne génère donc pas de migrations


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = "Catégorie"
        verbose_name_plural = "Catégories"


class Product(models.Model):
    code = models.BigIntegerField(verbose_name='Code', primary_key=True)
    name = models.CharField(verbose_name='Nom', max_length=100, unique=True)
    slug = models.SlugField(verbose_name='Slug', max_length=100)
    description = models.TextField(verbose_name='Description', max_length=500, unique=True)
    brand = models.CharField(verbose_name='Marque', max_length=30)
    url = models.URLField(verbose_name='URL', max_length=255, unique=True)
    nutriscore = models.CharField(verbose_name='Nutriscore', max_length=1)
    image = models.URLField(verbose_name='Image', )
    # image_small = models.URLField()

    categories = models.ManyToManyField(Category, related_name='products')

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = "Produit"
        verbose_name_plural = "Produits"


class Favorite(models.Model):
    username = models.CharField(max_length=150)
    code = models.BigIntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500, null=True)
    url = models.URLField(max_length=255, null=True)
    nutriscore = models.CharField(max_length=1, null=True)
    image = models.ImageField(null=True)

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = "Favori"
        verbose_name_plural = "Favoris"


# class PurBeurreUser(AbstractUser):
    # USERNAME_FIELD = 'email'

pur_beurre_lm/healthier_food/forms.py
#! /usr/bin/env python3
# coding: utf-8

from django.forms import ModelForm, TextInput, EmailInput, PasswordInput
from django.contrib.auth.models import User


class NewAccountForm(ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email", "password"]
        widgets = {
            'first_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex : Jean'}),
            'last_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex : Martin'}),
            'email': EmailInput(attrs={'class': 'form-control', 'placeholder': 'Ex : jean.martin@email.com'}),
            'password': PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Ex : 32hg65ez98hj'})
        }


class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            'username': TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex : jean.martin@email.com'}),
            'password': PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Ex : 32hg65ez98hj'})
        }

pur_beurre_lm/healthier_food/views.py
#! /usr/bin/env python3
# coding: utf-8

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from .models import Product, Category, Favorite
from .forms import NewAccountForm, LoginForm
from .params import max_products


def home(request):
    return render(request, 'healthier_food/pages/home.html')


def search(request):

    # Query submitted by user
    query = request.POST.get('query')

    if not query:
        context = {}

    else:
        unhealthy_products_list = []

        # Get unhealthy products (i.e. nutriscore = D ou E) which name contains user query
        unhealthy_products = Product.objects.filter((Q(name__icontains=query) | Q(description__icontains=query) | Q(brand__icontains=query)) & (Q(nutriscore="D") | Q(nutriscore="E")))[:max_products]
        for unhealthy_product in unhealthy_products:
            unhealthy_products_list.append(unhealthy_product)

        products = paginate(request, unhealthy_products_list, 6)

        context = {
            'query': query,
            'products': products
        }

    return render(request, 'healthier_food/pages/search.html', context)


def substitute(request, unhealthy_product_code):
    """ Select a list of healthy products sharing a maximum of categories with submitted unhealthy one """

    # Unhealthy product submitted by user
    unhealthy_product = get_object_or_404(Product, code=unhealthy_product_code)

    # Get healthy products sharing at least one category with unhealthy product
    healthy_products_list = []
    categories = unhealthy_product.categories.all()
    for category in categories:
        healthy_products = Product.objects.filter(categories=category).exclude(nutriscore="D").exclude(nutriscore="E")
        for healthy_product in healthy_products:
            if healthy_product not in healthy_products_list:
                healthy_products_list.append(healthy_product)

    # Count shared categories between healthy and unhealthy products
    shared_categories_counter = {}
    for healthy_product in healthy_products_list:
        shared_categories = []
        healthy_product_categories = healthy_product.categories.all()

        # Add shared categories in 'shared_categories' list
        for category in categories:
            if get_object_or_404(Category, name=category) in healthy_product_categories:
                shared_categories.append(category)

        # Make a correspondance between healthy product & number of shared categories
        shared_categories_counter[healthy_product] = len(shared_categories)

    try:
        # Get maximum number of shared categories
        maximum = max(shared_categories_counter.values())

        # Make a list of healthy products sharing the maximum number of categories with unhealthy product
        best_matches = []
        for healthy_product, number_of_shared_categories in shared_categories_counter.items():
            if number_of_shared_categories == maximum and len(best_matches) < max_products:
                best_matches.append(healthy_product)

        # Rearrange 'best_matches' list (putting "A"-products first)
        healthiest_first_list = []
        for match in best_matches:
            if match.nutriscore == "A":
                healthiest_first_list.append(match)
        for match in best_matches:
            if match.nutriscore == "B":
                healthiest_first_list.append(match)

        products = paginate(request, healthiest_first_list, 6)

    # If 'counter' is empty (i.e. no healthy product shares at least one category with unhealthy product)
    except ValueError as e:
        # Healthy products list is empty
        products = []

    context = {
        'unhealthy_product': unhealthy_product,
        'products': products
    }

    return render(request, 'healthier_food/pages/substitute.html', context)


def details(request, product_code):
    product = get_object_or_404(Product, code=product_code)

    # context = {
    #     'product': product
    # }

    return render(request, 'healthier_food/pages/details.html', locals())


def new_account(request):
    form = NewAccountForm()

    # context = {
    #     'form': form
    # }

    return render(request, 'healthier_food/pages/new_account.html', locals())


def account_creation(request):
    first_name = request.POST.get('first_name')
    last_name = request.POST.get('last_name')
    username = request.POST.get('email')
    email = request.POST.get('email')
    password = request.POST.get('password')

    contact = User.objects.filter(username=username)

    if not contact.exists():
        contact = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email, password=password)

        # context = {
        #     'contact': contact,
        # }

        return render(request, 'healthier_food/pages/account_success.html', locals())

    else:
        context = {
            'contact': contact[0],
        }

        return render(request, 'healthier_food/pages/account_failure.html', context)


def login_user(request):
    error = False
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data[('username')]
            password = form.cleaned_data[('password')]
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
            else:
                error = True
    else:
        form = LoginForm()

    return render(request, 'healthier_food/pages/login.html', locals())


def my_account(request):
    username = request.POST.get('username')
    password = request.POST.get('password')

    # contact = authenticate(username=username, password=password)
    contact = authenticate(username='Toto')
    # contact = {'username': 'Toto'}

    if contact:
        login(contact)

        context = {
            'contact': contact
        }

        return render(request, 'healthier_food/pages/my_account.html', context)

    else:
        return render(request, 'healthier_food/pages/login_failure.html')


def favorites(request):
    favorites = Favorite.objects.all()


    context = {
        'favorites': favorites
    }

    return render(request, 'healthier_food/pages/favorites.html', context)


def add_favorite(request, favorite_code):
    username = "Toto"

    # Check if favorite already in DB
    favorite = Favorite.objects.filter(code=favorite_code)

    if not favorite.exists():
        product = get_object_or_404(Product, code=favorite_code)
        favorite = Favorite.objects.create(username=username,
                                           code=product.code,
                                           name=product.name,
                                           description=product.description,
                                           url=product.url,
                                           nutriscore=product.nutriscore,
                                           image=product.image
                                           )

        # context = {
        #     'favorite': favorite
        # }

        return render(request, 'healthier_food/pages/favorite_success.html', locals())


def logout_user(request):
    logout(request)
    return render(request, 'healthier_food/pages/logout.html')


def paginate(request, product_list, nb):
    """ Not a view but a function to factorise pagination code """
    paginator = Paginator(product_list, nb)
    page = request.GET.get('page')

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    return products

pur_beurre_lm/healthier_food/templates/healthier_food/pages/account_failure.html
{% extends 'layouts/base.html' %}

{% block content %}

<header class="home_bg masthead text-center text-white d-flex">
  <div class="container my-auto">

    <div class="row">
      <div class="col-lg-10 mx-auto">
        <h1 class="text-uppercase">
          <strong>Un compte existant est déjà associé au nom d'utilisateur "{{ contact.username }}"</strong>
        </h1>
        <hr>

        <div class="col-lg-8 mx-auto">
          <h2 class="text-faded mb-5">Vous pouvez recommencer en choisissant un autre nom d'utilisateur ou essayer de vous connecter à un compte existant</h2>

          <a class="btn btn-light btn-xl sr-button" href="{% url 'healthier_food:new_account' %}">Créer un nouveau compte</a>
          <a class="btn btn-light btn-xl sr-button" href="{% url 'healthier_food:login' %}">Se connecter</a>

        </div>


      </div>
    </div>

  </div>
</header>

{% endblock %}

pur_beurre_lm/healthier_food/templates/healthier_food/pages/account_success.html
{% extends 'layouts/base.html' %}

{% block content %}

<header class="home_bg masthead text-center text-white d-flex">
  <div class="container my-auto">

    <div class="row">
      <div class="col-lg-10 mx-auto">
        <h1 class="text-uppercase">
          <strong>Félicitations {{ contact.first_name }} ! Votre compte est désormais créé !</strong>
        </h1>
        <hr>
      </div>
    </div>

  </div>
</header>

{% endblock %}

pur_beurre_lm/healthier_food/templates/healthier_food/pages/details.html
{% extends 'layouts/base.html' %}

{% block content %}


<header class="detail_bg masthead text-center text-white d-flex">
  <div class="container my-auto">
    <div class="row">
      <div class="col-lg-10 mx-auto">
        <img src="{{ product.image }}">
        <h2 class="text-uppercase">
          <strong>{{ product.name }}</strong>
        </h2>
        <h3 class="text-uppercase">
          ({{ product.description }})
        </h3>
        <hr>
      </div>
    </div>
  </div>
</header>

<section id="services">
  <div class="container">
    <div class="row">

      <div class="col-lg-6 col-md-3 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-diamond text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">Nutriscore</h3>
          <p class="text-muted mb-0">{{ product.nutriscore }}</p>
        </div>
      </div>

      <div class="col-lg-6 col-md-3 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-paper-plane text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">Repères nutritionnels pour 100 g</h3>
          <p class="text-muted mb-0">{{ product.energy }}</p>
        </div>
      </div>

      <div class="col-lg-4 mx-auto">
        <a class="btn btn-primary btn-xl js-scroll-trigger" href={{ product.url }}>Voir la fiche Open Food Facts</a>
      </div>


    </div>


    <div class="col-lg-4 mx-auto">
      <a class="btn btn-light btn-xl sr-button" href="{% url 'healthier_food:add_favorite' favorite_code=product.code %}">Ajouter aux favoris</a>
    </div>




  </div>
</section>

{% endblock %}

pur_beurre_lm/healthier_food/templates/healthier_food/pages/favorite_success.html
{% extends 'layouts/base.html' %}

{% block content %}

<header class="home_bg masthead text-center text-white d-flex">
  <div class="container my-auto">

    <div class="row">
      <div class="col-lg-10 mx-auto">
        <h1 class="text-uppercase">
          <strong>{{ favorite.name }} vient d'être ajouté à vos produits favoris</strong>
        </h1>
        <hr>
      </div>
    </div>

  </div>
</header>

{% endblock %}

pur_beurre_lm/healthier_food/templates/healthier_food/pages/favorites.html
{% extends 'layouts/base.html' %}

{% block content %}
    <header class="search_bg masthead text-white d-flex">
        <div class="container-fluid my-auto">
            <div class="row">Voici vos aliments favoris :
            </div>
            <div class="row">
                {% for favorite in favorites %}
                    <p class="col-xs-12 col-sm-6 col-md-4 col-lg-4 text-uppercase text-center">

                        <img src="{{ favorite.image }}"><br><strong>{{ favorite.name }} - {{ favorite.nutriscore }}</strong>
                        <div class="col-lg-4 mx-auto">
                            <a class="btn btn-primary btn-xl js-scroll-trigger" href={{ favorite.url }}>Voir la fiche Open Food Facts</a>
                        </div>
                    </p>
                    {% if not forloop.last %}
                        <hr>
                    {% endif %}

                    {% empty %}
                        <p>Aucun aliment favori enregistré</p>
                {% endfor %}
            </div>
        </div>
    </header>
{% endblock %}

pur_beurre_lm/healthier_food/templates/healthier_food/pages/home.html
{% extends 'layouts/base.html' %}

{% block content %}

<header class="home_bg masthead text-center text-white d-flex">
  <div class="container my-auto">

    <div class="row">
      <div class="col-lg-10 mx-auto">
        <h1 class="text-uppercase">
          <strong>Du gras, oui, mais de qualité !</strong>
        </h1>
        <hr>
      </div>
      <div class="col-lg-8 mx-auto">
        <h2 class="text-faded mb-5">Trouvez un produit de substitution pour ceux que vous consommez tous les jours</h2>
      </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">

            <form action="{% url 'healthier_food:search' %}" method="post" accept-charset="utf-8">
                {% csrf_token %}

                <div class="form-group">
                    <input id="searchForm" class="form-control" name="query" placeholder="Ex : Pizza">
                </div>
            </form>

        </div>
    </div>

  </div>
</header>

<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Colette & Rémy Tatou</h2>
        <hr class="my-4">
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-3 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-diamond text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">Colette</h3>
          <p class="text-muted mb-0">"Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"</p>
        </div>
      </div>
      <div class="col-lg-6 col-md-3 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-paper-plane text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">Rémy</h3>
          <p class="text-muted mb-0">"Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="bg-dark text-white">
  <div class="container text-center">
    <h2 class="mb-4">Contactez-nous !</h2>
    <a class="btn btn-light btn-xl sr-button" href="http://startbootstrap.com/template-overviews/creative/">mail@mail.com</a>
  </div>
</section>

{% endblock %}

pur_beurre_lm/healthier_food/templates/healthier_food/pages/legal_notice.html
<p>&copy; Copyright {% now 'Y' %} &middot; Pur Beurre &middot; All rights reserved</p>

pur_beurre_lm/healthier_food/templates/healthier_food/pages/login.html
{% extends 'layouts/base.html' %}

{% block content %}

<header class="home_bg masthead text-center text-white d-flex">
  <div class="container my-auto">

    <div class="row">
      <div class="col-lg-10 mx-auto">
        <h1 class="text-uppercase">
          <strong>Connectez-vous à votre compte !</strong>
        </h1>
        <hr>
      </div>
      <div class="col-lg-8 mx-auto">
        <h2 class="text-faded mb-5">Entrez votre nom d'utilisateur et votre mot de passe</h2>
      </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">

            {% if error %}
                <p><strong>Désolé, les informations saisies ne sont associées à aucun compte existant</strong></p>
            {% endif %}

{% comment %}
    La variable 'user' dans les templates est ajoutée par un processeur de contexte inclus par défaut. Le même objet est disponible via 'request.user' dans les vues.
{% endcomment %}

            {% if user.is_authenticated %}
                Vous êtes connecté, {{ user.username }}

            {% else %}

                <form action="{% url 'healthier_food:my_account' %}" method="post" accept-charset="utf-8">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="{{ form.username.id_for_label }}" class="control-label">Adresse email</label>
                        {{ form.username }}
                    </div>

                    <div class="form-group">
                        <label for="{{ form.last_name.id_for_label }}" class="control-label">Mot de passe</label>
                        {{ form.password }}

                    </div>
                    <button type="submit" class="btn btn-success">Se connecter</button>
                </form>

            {% endif %}



        </div>

        <div class="col-lg-8 mx-auto">
          <h2 class="text-faded mb-5">Pas encore de compte ?</h2>

          <a class="btn btn-light btn-xl sr-button" href="{% url 'healthier_food:new_account' %}">Créez-en un ici !</a>

        </div>

    </div>

  </div>
</header>

{% endblock %}

pur_beurre_lm/healthier_food/templates/healthier_food/pages/login_failure.html
{% extends 'layouts/base.html' %}

{% block content %}

<header class="home_bg masthead text-center text-white d-flex">
  <div class="container my-auto">

    <div class="row">
      <div class="col-lg-10 mx-auto">
        <h1 class="text-uppercase">
          <strong>Désolé, les informations saisies ne sont associées à aucun compte existant</strong>
        </h1>
        <hr>
      </div>

      <div class="col-lg-8 mx-auto">
        <a class="btn btn-light btn-xl sr-button" href="{% url 'healthier_food:login' %}">Réessayez de vous connecter</a>
        <a class="btn btn-light btn-xl sr-button" href="{% url 'healthier_food:new_account' %}">Créez un nouveau compte</a>
      </div>

    </div>
  </div>
</header>

{% endblock %}

pur_beurre_lm/healthier_food/templates/healthier_food/pages/logout.html
{% extends 'layouts/base.html' %}

{% block content %}

<header class="home_bg masthead text-center text-white d-flex">
  <div class="container my-auto">

    <div class="row">
      <div class="col-lg-10 mx-auto">
        <h1 class="text-uppercase">
          <strong>Vous êtes maintenant déconnecté !</strong>
        </h1>
        <hr>
      </div>
    </div>

  </div>
</header>

{% endblock %}

pur_beurre_lm/healthier_food/templates/healthier_food/pages/my_account.html
{% extends 'layouts/base.html' %}

{% block content %}

<header class="detail_bg masthead text-center text-white d-flex">
  <div class="container my-auto">
    <div class="row">
      <div class="col-lg-10 mx-auto">
        <img src="{{ product.image }}">
        <h2 class="text-uppercase">
          <strong>Bonjour {{ contact.username }}</strong>
        </h2>
        <h3 class="text-uppercase">
          <strong>Bienvenue dans votre espace personnel !</strong>
        </h3>
        <hr>
      </div>
    </div>
  </div>
</header>

<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 mx-auto">
        <a class="btn btn-primary btn-xl js-scroll-trigger">Votre email : {{ contact.email }}</a>
      </div>

    </div>
  </div>
</section>

{% endblock %}

pur_beurre_lm/healthier_food/templates/healthier_food/pages/new_account.html
{% extends 'layouts/base.html' %}

{% block content %}

<header class="home_bg masthead text-center text-white d-flex">
  <div class="container my-auto">

    <div class="row">
      <div class="col-lg-10 mx-auto">
        <h1 class="text-uppercase">
          <strong>Créez un nouveau compte !</strong>
        </h1>
        <hr>
      </div>
      <div class="col-lg-8 mx-auto">
        <h2 class="text-faded mb-5">Entrez votre nom d'utilisateur et votre mot de passe</h2>
      </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">
            <form action="{% url 'healthier_food:account_creation' %}" method="post" accept-charset="utf-8">
                {% csrf_token %}

                <div class="form-group">
                    <label for="{{ form.first_name.id_for_label }}" class="control-label">Prénom</label>
                    {{ form.first_name }}
                </div>

                <div class="form-group">
                    <label for="{{ form.last_name.id_for_label }}" class="control-label">Nom</label>
                    {{ form.last_name }}
                </div>

                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}" class="control-label">Adresse email</label>
                    {{ form.email }}
                </div>

                <div class="form-group">
                    <label for="{{ form.password.id_for_label }}" class="control-label">Mot de passe</label>
                    {{ form.password }}
                </div>

                <button type="submit" class="btn btn-success">Créer</button>
            </form>
        </div>
    </div>

  </div>
</header>

{% endblock %}

pur_beurre_lm/healthier_food/templates/healthier_food/pages/search.html
{% extends 'healthier_food/layouts/products_display.html' %}








{% block sentence %}
    <div class="row">Voici les produit{{ products|length|pluralize }} correspondants à la recherche "{{ query }}" - Lequel voulez-vous substituer ?
    </div>
{% endblock %}

{% block product_to_display %}
    <a href="{% url 'healthier_food:substitute' unhealthy_product_code=product.code %}"><img src="{{ product.image }}"><br><strong>{{ product.name }} - {{ product.nutriscore }}</strong></a>
{% endblock %}

{% block if_empty_sentence %}
    <p>Aucun produit ne correspond à votre recherche</p>
{% endblock %}

{% block url_for_previous %}
    <li><a href="?query={{ query }}&page={{ products.previous_page_number }}">Précédent</a></li>
{% endblock %}

{% block url_for_next %}
    <li><a href="?query={{ query }}&page={{ products.next_page_number }}">Suivant</a></li>
{% endblock %}

pur_beurre_lm/healthier_food/templates/healthier_food/pages/substitute.html
{% extends 'healthier_food/layouts/products_display.html' %}

{% block product_to_replace %}
    <div class="row moules">
        <h2 class="col-md-12">{{ unhealthy_product }}</h2>
        <img src="{{ unhealthy_product.image }}" class="col-md-2">
    </div>
{% endblock %}

{% block sentence %}
    <div class="row">Vous pouvez remplacer "{{ unhealthy_product }}" par :
    </div>
{% endblock %}

{% block product_to_display %}
    <a href="{% url 'healthier_food:details' product_code=product.code %}"><img src="{{ product.image }}"><br><strong>{{ product.name }} - {{ product.nutriscore }}</strong><br></a>

    <a class="btn btn-light btn-xl sr-button" href="{% url 'healthier_food:add_favorite' favorite_code=product.code %}">Ajouter aux favoris</a>
{% endblock %}

{% block if_empty_sentence %}
    <p>Aucune proposition de substitut satisfaisante :-(</p>
{% endblock %}

{% block url_for_previous %}
    <li><a href="?page={{ products.previous_page_number }}">Précédent</a></li>
{% endblock %}

{% block url_for_next %}
    <li><a href="?page={{ products.next_page_number }}">Suivant</a></li>
{% endblock %}