pur_beurre_lm/healthier_food/urls.py
#! /usr/bin/env python3
# coding: utf-8

from django.urls import path

from . import views

urlpatterns = [
    path('search', views.search, name='search'),
    path('substitute/<int:unhealthy_product_code>', views.substitute, name='substitute'),
    path('details/<int:product_code>', views.details, name='details'),
    path('new_account', views.new_account, name='new_account'),
    path('account_creation', views.account_creation, name='account_creation'),
    path('login', views.login_user, name='login'),
    path('my_account', views.my_account, name='my_account'),
    path('favorites', views.favorites, name='favorites'),
    path('add_favorite/<int:favorite_code>', views.add_favorite, name='add_favorite'),
    path('logout', views.logout_user, name='logout'),
]

pur_beurre_lm/pur_beurre_lm/urls.py
#! /usr/bin/env python3
# coding: utf-8

"""pur_beurre_lm URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from healthier_food import views

urlpatterns = [
    path('home/', views.home),
    path('healthier_food/', include(('healthier_food.urls', 'healthier_food'), namespace='healthier_food')),
    # path('admin/', admin.site.urls), on change le nom de la route 'admin' par défaut pour un minimum de sécurité
    path('admin_purbeurre/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

pur_beurre_lm/healthier_food/models.py
#! /usr/bin/env python3
# coding: utf-8

from django.db import models
# from django.contrib.auth.models import AbstractUser


# class TimestampedModel(models.Model):
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     class Meta:
#         abstract = True  # Une classe abstraite ne peut pas être instanciée. Django ne la considère donc pas comme un modèle à part entière, il ne génère donc pas de migrations


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = "Catégorie"
        verbose_name_plural = "Catégories"


class Product(models.Model):
    code = models.BigIntegerField(verbose_name='Code', primary_key=True)
    name = models.CharField(verbose_name='Nom', max_length=100, unique=True)
    slug = models.SlugField(verbose_name='Slug', max_length=100)
    description = models.TextField(verbose_name='Description', max_length=500, unique=True)
    brand = models.CharField(verbose_name='Marque', max_length=30)
    url = models.URLField(verbose_name='URL', max_length=255, unique=True)
    nutriscore = models.CharField(verbose_name='Nutriscore', max_length=1)
    image = models.URLField(verbose_name='Image', )
    # image_small = models.URLField()

    categories = models.ManyToManyField(Category, related_name='products')

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = "Produit"
        verbose_name_plural = "Produits"


class Favorite(models.Model):
    username = models.CharField(max_length=150)
    code = models.BigIntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500, null=True)
    url = models.URLField(max_length=255, null=True)
    nutriscore = models.CharField(max_length=1, null=True)
    image = models.ImageField(null=True)

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = "Favori"
        verbose_name_plural = "Favoris"


# class PurBeurreUser(AbstractUser):
    # USERNAME_FIELD = 'email'

pur_beurre_lm/healthier_food/forms.py
#! /usr/bin/env python3
# coding: utf-8

from django.forms import ModelForm, TextInput, EmailInput, PasswordInput
from django.contrib.auth.models import User


class NewAccountForm(ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email", "password"]
        widgets = {
            'first_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex : Jean'}),
            'last_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex : Martin'}),
            'email': EmailInput(attrs={'class': 'form-control', 'placeholder': 'Ex : jean.martin@email.com'}),
            'password': PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Ex : 32hg65ez98hj'})
        }


class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            'username': TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex : jean.martin@email.com'}),
            'password': PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Ex : 32hg65ez98hj'})
        }

pur_beurre_lm/healthier_food/views.py
#! /usr/bin/env python3
# coding: utf-8

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from .models import Product, Category, Favorite
from .forms import NewAccountForm, LoginForm
from .params import max_products


def home(request):
    return render(request, 'healthier_food/pages/home.html')


def search(request):

    # Query submitted by user
    query = request.POST.get('query')

    if not query:
        context = {}

    else:
        unhealthy_products_list = []

        # Get unhealthy products (i.e. nutriscore = D ou E) which name contains user query
        unhealthy_products = Product.objects.filter((Q(name__icontains=query) | Q(description__icontains=query) | Q(brand__icontains=query)) & (Q(nutriscore="D") | Q(nutriscore="E")))[:max_products]
        for unhealthy_product in unhealthy_products:
            unhealthy_products_list.append(unhealthy_product)

        products = paginate(request, unhealthy_products_list, 6)

        context = {
            'query': query,
            'products': products
        }

    return render(request, 'healthier_food/pages/search.html', context)


def substitute(request, unhealthy_product_code):
    """ Select a list of healthy products sharing a maximum of categories with submitted unhealthy one """

    # Unhealthy product submitted by user
    unhealthy_product = get_object_or_404(Product, code=unhealthy_product_code)

    # Get healthy products sharing at least one category with unhealthy product
    healthy_products_list = []
    categories = unhealthy_product.categories.all()
    for category in categories:
        healthy_products = Product.objects.filter(categories=category).exclude(nutriscore="D").exclude(nutriscore="E")
        for healthy_product in healthy_products:
            if healthy_product not in healthy_products_list:
                healthy_products_list.append(healthy_product)

    # Count shared categories between healthy and unhealthy products
    shared_categories_counter = {}
    for healthy_product in healthy_products_list:
        shared_categories = []
        healthy_product_categories = healthy_product.categories.all()

        # Add shared categories in 'shared_categories' list
        for category in categories:
            if get_object_or_404(Category, name=category) in healthy_product_categories:
                shared_categories.append(category)

        # Make a correspondance between healthy product & number of shared categories
        shared_categories_counter[healthy_product] = len(shared_categories)

    try:
        # Get maximum number of shared categories
        maximum = max(shared_categories_counter.values())

        # Make a list of healthy products sharing the maximum number of categories with unhealthy product
        best_matches = []
        for healthy_product, number_of_shared_categories in shared_categories_counter.items():
            if number_of_shared_categories == maximum and len(best_matches) < max_products:
                best_matches.append(healthy_product)

        # Rearrange 'best_matches' list (putting "A"-products first)
        healthiest_first_list = []
        for match in best_matches:
            if match.nutriscore == "A":
                healthiest_first_list.append(match)
        for match in best_matches:
            if match.nutriscore == "B":
                healthiest_first_list.append(match)

        products = paginate(request, healthiest_first_list, 6)

    # If 'counter' is empty (i.e. no healthy product shares at least one category with unhealthy product)
    except ValueError as e:
        # Healthy products list is empty
        products = []

    context = {
        'unhealthy_product': unhealthy_product,
        'products': products
    }

    return render(request, 'healthier_food/pages/substitute.html', context)


def details(request, product_code):
    product = get_object_or_404(Product, code=product_code)

    # context = {
    #     'product': product
    # }

    return render(request, 'healthier_food/pages/details.html', locals())


def new_account(request):
    form = NewAccountForm()

    # context = {
    #     'form': form
    # }

    return render(request, 'healthier_food/pages/new_account.html', locals())


def account_creation(request):
    first_name = request.POST.get('first_name')
    last_name = request.POST.get('last_name')
    username = request.POST.get('email')
    email = request.POST.get('email')
    password = request.POST.get('password')

    contact = User.objects.filter(username=username)

    if not contact.exists():
        contact = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email, password=password)

        # context = {
        #     'contact': contact,
        # }

        return render(request, 'healthier_food/pages/account_success.html', locals())

    else:
        context = {
            'contact': contact[0],
        }

        return render(request, 'healthier_food/pages/account_failure.html', context)


def login_user(request):
    error = False
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data[('username')]
            password = form.cleaned_data[('password')]
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
            else:
                error = True
    else:
        form = LoginForm()

    return render(request, 'healthier_food/pages/login.html', locals())


def my_account(request):
    username = request.POST.get('username')
    password = request.POST.get('password')

    # contact = authenticate(username=username, password=password)
    contact = authenticate(username='Toto')
    # contact = {'username': 'Toto'}

    if contact:
        login(contact)

        context = {
            'contact': contact
        }

        return render(request, 'healthier_food/pages/my_account.html', context)

    else:
        return render(request, 'healthier_food/pages/login_failure.html')


def favorites(request):
    favorites = Favorite.objects.all()


    context = {
        'favorites': favorites
    }

    return render(request, 'healthier_food/pages/favorites.html', context)


def add_favorite(request, favorite_code):
    username = "Toto"

    # Check if favorite already in DB
    favorite = Favorite.objects.filter(code=favorite_code)

    if not favorite.exists():
        product = get_object_or_404(Product, code=favorite_code)
        favorite = Favorite.objects.create(username=username,
                                           code=product.code,
                                           name=product.name,
                                           description=product.description,
                                           url=product.url,
                                           nutriscore=product.nutriscore,
                                           image=product.image
                                           )

        # context = {
        #     'favorite': favorite
        # }

        return render(request, 'healthier_food/pages/favorite_success.html', locals())


def logout_user(request):
    logout(request)
    return render(request, 'healthier_food/pages/logout.html')


def paginate(request, product_list, nb):
    """ Not a view but a function to factorise pagination code """
    paginator = Paginator(product_list, nb)
    page = request.GET.get('page')

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    return products

pur_beurre_lm/healthier_food/templates/healthier_food/layouts/_nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="/home/"><img class="logo" src="{% static 'healthier_food/img/logo_pur_beurre-favicon.png' %}" alt="logo"/>Pur Beurre</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger">

            <div class="col-md-12 text-center">
                <form action="{% url 'healthier_food:search' %}" method="post" accept-charset="utf-8">
                  {% csrf_token %}


                    <div class="form-group">
                        <input id="searchForm" class="form-control" name="query" placeholder="Chercher un produit">
                    </div>
                </form>
            </div>
          </a>
        </li>



        {% if request.user.is_authenticated %}
        {# {% if 1 == 2 %} #}

          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'healthier_food:my_account' %}">Mon compte</a>
          </li>

          <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'healthier_food:favorites' %}">Mes aliments</a>
          </li>

          <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="{% url 'healthier_food:logout' %}">Déconnexion</a>
          </li>

        {% else %}

          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'healthier_food:login' %}">Se connecter</a>
          </li>


        {% endif %}


      </ul>
    </div>
  </div>
</nav>

pur_beurre_lm/healthier_food/templates/healthier_food/layouts/products_display.html
{% extends 'layouts/base.html' %}

{% block content %}

    <header class="search_bg masthead text-center text-white d-flex">

        <div class="container-fluid my-auto">

            {% block product_to_replace %}{% endblock %}

            {% block sentence %}{% endblock %}

            <div class="row">

                {% for product in products %}

                    <p class="col-xs-12 col-sm-6 col-md-4 col-lg-4 text-uppercase text-center">
                        {% block product_to_display %}{% endblock %}
                    </p>

                    {% if not forloop.last %}
                        <hr>
                    {% endif %}

                    {% empty %}
                        {% block if_empty_sentence %}{% endblock %}

                {% endfor %}

            </div>

            <nav aria-label="">

                <ul class="pager">

                    {% if products.has_previous %}
                        {% block url_for_previous %}{% endblock %}

                    {% endif %}

                    {% if products.has_next %}
                        {% block url_for_next %}{% endblock %}

                    {% endif %}

                </ul>

            </nav>

        </div>
    </header>

{% endblock %}